apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securtiyContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: elasticsearch-pvc
          PersistentVolumeReclaimPolicy:
            claimName: elasticsearch-pvc
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
          env:
            - name: discovery.type
              value: single-node
            - name: ELASTIC_PASSWORD
              value: change_me
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: 9200
            - containerPort: 9300
          volumeMounts:
            - name: elasticsearch-pvc
              mountPath: /usr/share/elasticsearch/data
        - name: kibana
          image: kibana:8.12.0
          env:
            - name: ELASTICSEARCH_HOSTS
              value: '["http://localhost:9200"]'
            - name: ELASTICSEARCH_USERNAME
              value: kibana_system
            - name: ELASTICSEARCH_PASSWORD
              value: change_me
          ports:
            - containerPort: 5601

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  ports:
    - name: rest-api
      port: 9200
      targetPort: 9200
    - name: kibana
      port: 5601
      targetPort: 5601
  selector:
    app: elasticsearch
