apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  PersistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /mnt/storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node
  claimRef:
    name: elasticsearch-pvc
    namespace: elasticsearch
