apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: elasticsearch
spec:
  storageClassName: ""
  volumeName: elasticsearch-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
