- name: Assert variables
  assert:
    that:
      - hostname is defined
      - old_hostname is defined

- name: Assign hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Replace old hostname in /etc/hosts
  become: true
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '(\s+){{ old_hostname }}(\s+.*)?$'
    replace: '\1{{ hostname }}\2'
