apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  namespace: downloader
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  PersistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /mnt/downloader/kafka
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node
  claimRef:
    name: kafka-pvc
    namespace: downloader

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: downloader
spec:
  storageClassName: ""
  volumeName: kafka-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
