- name: Set facts
  ansible.builtin.set_fact:
    k8s_config: /etc/rancher/rke2/rke2.yaml
    temp_config: /home/{{ ansible_user }}/kubeconfig.yaml
    cert_manager_yaml: /home/{{ ansible_user }}/cert_manager.yaml

- name: install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes

- name: Configure Kubernetes
  environment:
    KUBECONFIG: "{{ temp_config }}"
  block:
    - name: Allow kubectl access to K8s config
      become: true
      shell: |
        cp {{ k8s_config }} {{ temp_config }}
        chown {{ ansible_user }}:{{ ansible_user }} {{ temp_config }}

    - name: Add Helm charts for K8s
      kubernetes.core.helm_repository:
        name: rancher-stable
        repo_url: https://releases.rancher.com/server-charts/stable

    - name: Create cattle-system namespace
      kubernetes.core.k8s:
        name: cattle-system
        api_version: v1
        kind: Namespace
        state: present

    - name: Download cert-manager config
      ansible.builtin.get_url:
        url: https://github.com/cert-manager/cert-manager/releases/download/v1.13.3/cert-manager.crds.yaml
        dest: "{{ cert_manager_yaml }}"

    - name: Install cert-manager
      kubernetes.core.k8s:
        state: present
        src: "{{ cert_manager_yaml }}"

    - name: Delete cert-manager config
      ansible.builtin.file:
        path: "{{ cert_manager_yaml }}"
        state: absent

    - name: Add Jetstack Helm repo
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io

    - name: Install cert-manager Helm chart
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        create_namespace: true

    - name: Install Rancher with Helm and cert-manager
      kubernetes.core.helm:
        name: rancher
        chart_ref: rancher-stable/rancher
        release_namespace: cattle-system
        set_values:
          - value: hostname=rancher.homelab.local
            value_type: string

  # Some bug where this won't set access to root only
  always:
    - name: Remove kubectl access to K8s config
      ansible.builtin.file:
        path: "{{ temp_config }}"
        state: absent
