- ansible.builtin.include_tasks: install_pip.yml

- name: Expand partition
  become: true
  shell: |
    growpart /dev/sda 3
  ignore_errors: true

- name: Resize LVM disk space
  become: true
  community.general.lvol:
    vg: ubuntu-vg
    lv: ubuntu-lv
    size: +100%FREE
    resizefs: true

- name: Assign hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Replace old hostname in /etc/hosts
  become: true
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '(\s+){{ old_hostname }}(\s+.*)?$'
    replace: '\1{{ hostname }}\2'
