- name: All ubuntu servers
  hosts: [proxy, bastion, k8s_server, k8s_node]
  tasks:
    - name: Expand partition
      become: true
      shell: |
        growpart /dev/sda 3
      ignore_errors: true

    - name: Resize LVM disk space
      become: true
      community.general.lvol:
        vg: ubuntu-vg
        lv: ubuntu-lv
        size: +100%FREE
        resizefs: true
