apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      volumes:
        - name: opensearch-pvc
          PersistentVolumeReclaimPolicy:
            claimName: opensearch-pvc
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:latest
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
            - containerPort: 9600
          volumeMounts:
            - name: opensearch-pvc
              mountPath: /usr/share/opensearch/data
