apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pvc
  namespace: opensearch
spec:
  storageClassName: ""
  volumeName: opensearch-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
