---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: opensearch-pvc
          PersistentVolumeReclaimPolicy:
            claimName: opensearch-pvc
        - name: opensearch-config
          secret:
            secretName: opensearch-internal-users-config
        - name: opensearch-dashboards-config
          secret:
            secretName: opensearch-dashboards-config
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:latest
          env:
            - name: discovery.type
              value: single-node
            - name: plugins.security.ssl.http.enabled
              value: "false"
          ports:
            - containerPort: 9200
            - containerPort: 9600
          volumeMounts:
            - name: opensearch-pvc
              mountPath: /usr/share/opensearch/data
            - name: opensearch-config
              mountPath: /mnt/config
          resources:
            limits:
              cpu: 1
              memory: 2Gi
              ephemeral-storage: 8Gi
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /mnt/config/internal_users.yml /usr/share/opensearch/config/opensearch-security/internal_users.yml
        - name: opensearch-dashboards
          image: opensearchproject/opensearch-dashboards:latest
          ports:
            - containerPort: 5601
          volumeMounts:
            - name: opensearch-dashboards-config
              mountPath: /mnt/dashboard-config
          resources:
            limits:
              cpu: 1
              memory: 1Gi
              ephemeral-storage: 8Gi
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /mnt/dashboard-config/opensearch_dashboards.yml /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml

---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: opensearch
spec:
  ports:
    - name: rest-api
      port: 9200
      targetPort: 9200
    - name: dashboard
      port: 5601
      targetPort: 5601
  selector:
    app: opensearch
