apiVersion: v1
kind: ConfigMap
metadata:
  name: clamd-client-config
  namespace: clamav
data:
  clamd.conf: |
    TCPSocket 3310
    TCPAddr clamd

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner
  namespace: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: clamd-client-config
          configMap:
            name: clamd-client-config
      containers:
        - name: scanner-api
          image: rbyrne30/malware-scanner:0.0.3
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: clamd-client-config
              mountPath: /etc/clamav
              readOnly: true
          resources:
            limits:
              cpu: 1
              memory: 1Gi
              ephemeral-storage: 8Gi

---
apiVersion: v1
kind: Service
metadata:
  name: scanner
  namespace: clamav
spec:
  ports:
    - name: scanner
      port: 9000
      targetPort: 9000
  selector:
    app: scanner
