- name: Create Rancher directory
  become: true
  shell: |
    mkdir -p /etc/rancher/rke2

- name: Create config file
  become: true
  ansible.builtin.template:
    src: "config.j2"
    dest: /etc/rancher/rke2/config.yaml

- name: Check if RKE2 service exists
  systemd:
    name: rke2-server
  register: rke2_service

# - name: Display RKE2 service status
#   debug:
#     var: rke2_service

- name: Install RKE2
  become: true
  shell: |
    export INSTALL_RKE2_METHOD=tar 
    curl -sfL https://get.rke2.io | sh -
  when: rke2_service.status.ActiveState != "active"

- name: Enable RKE2 service
  become: true
  shell: |
    systemctl enable rke2-server.service
  when: rke2_service.status.ActiveState != "active"

- name: Start RKE2 service
  become: true
  shell: |
    systemctl start rke2-server.service
  when: rke2_service.status.ActiveState != "active"
